REVOKE EXECUTE ON FUNCTION public.has_role(UUID, public.app_role) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.ws_role(UUID) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_ws_member(UUID) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.can_edit_ws(UUID) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.can_manage_ws(UUID) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_ws_owner(UUID) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.create_workspace(TEXT, NUMERIC) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.list_ws_members(UUID) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.has_role(UUID, public.app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ws_role(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_ws_member(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_edit_ws(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_manage_ws(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_ws_owner(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_workspace(TEXT, NUMERIC) TO authenticated;
GRANT EXECUTE ON FUNCTION public.list_ws_members(UUID) TO authenticated;